---
title: "Simulations"
author: "Julian Frattini"
date: '2025-04-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
```

This notebook explains the fundamentals of **data set simulations**, a powerful tool to create a reliable ground truth.

```{r}
n <- 1000

d <- data.frame(
  technique = rep(0:1, n/2)
) %>% mutate(
  defects = rnorm(n, 5 + 5*technique, 2)
)
```

```{r}
d$technique <- factor(d$technique, levels = c(0, 1), ordered = FALSE)
```


```{r}
ggplot(data = d, mapping = aes(y = technique)) +
  geom_histogram(stat = "count")
  

ggsave(filename = "simulation-marginal-technique.png", device = "png", units = "cm", width = 10, height = 3)
```


```{r}
ggplot(data = d, mapping = aes(x = defects)) +
  geom_histogram(stat = "bin", bins = 50)


ggsave(filename = "simulation-defects-combined.png", device = "png", units = "cm", width = 10, height = 5.5)
```

```{r}
ggplot(data = d, mapping = aes(x = defects, fill = technique)) +
  geom_histogram(stat = "bin", bins = 50) +
    theme(legend.position="bottom")


ggsave(filename = "simulation-defects-split.png", device = "png", units = "cm", width = 10, height = 7)
```

```{r}
results <- lm(defects ~ technique, data = d)
confint(results)
```

