---
title: "Colliding"
author: "Julian Frattini"
date: "2025-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(ggdag)

# utility methods for extracting coefficient distributions from two models
source("../util/extract-coefficients.R")
```

This notebook visualizes the effect of common effects (also called *colliders*) in causal inference.

```{r configuration}
varname.a <- "Variable A"
varname.b <- "Variable B"
varname.c <- "Variable C"

effect.ab <- 0
threshold <- 0.7
```

```{r dag}
dag <- dagify(
  b ~ a , # (assumed) causal effect of the independent on the dependent variable
  c ~ a + b, # colliding effect of both these variables on a third variable
  exposure = "a", outcome = "b",
  
  labels = c(a = varname.a, b = varname.b, c = varname.c),
  coords = list(x = c(a = 0, b = 2, c = 1), 
                y = c(a = 1, b = 1, c = 0))
)

ggdag_status(dag, use_labels = "label", text = FALSE) +
  guides(fill = "none", color = "none") + 
  theme_dag()
```

```{r simulation}
n <- 1000

d <- data.frame(a = rnorm(n, 0, 1)) %>% 
  mutate(
    b = rnorm(n, 0 + effect.ab*a, 1),
    c = (a + b > threshold)
  )
```

```{r model-biased}
m2 <- lm( 
  formula = b ~ a + c,
  data = d
)

summary(m2)
```

```{r visualization-complete}
ggplot(d, aes(x = a, y = b)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_smooth(formula = (y ~ x), method = 'lm') + 
  labs(x = varname.a, y = varname.b) +
  theme_bw()
```

```{r visualization stratified}
ggplot(d, aes(x = a, y = b, color = factor(c))) +
  geom_point() +
  geom_smooth(formula = (y ~ x), method = 'lm') + 
  geom_abline(intercept = threshold, slope = -1, linetype = "dashed") + 
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  labs(x = varname.a, y = varname.b, color = varname.c) + 
  theme_bw()
```



```{r model-correct}
m1 <- lm(formula = b ~ a, data = d)
summary(m1)
```
```{r visualization-coefficients}
get.coefficient.distributions(m1, m2, "Model m1 (unbiased)", "Model m2 (biased)") %>% 
  ggplot(aes(y = factor)) +
    geom_point(aes(x = estimate)) + 
    geom_errorbar(aes(xmin = lower, xmax = upper)) +
    geom_vline(xintercept = effect.ab, linetype = "dashed", color = "cyan", size = 0.9) + 
    facet_wrap(vars(model), ncol=1) +
  labs(x = "Estimated effect", y = "Factors") +
  scale_y_discrete(labels = c(varname.a, varname.c)) +
  theme_bw()
```

