---
title: "Confounding"
author: "Julian Frattini"
date: "2025-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(ggdag)
```

This notebook visualizes the effect of common causes (also called *forks* and *confounders*) in causal inference.
Forks are one of the most common sources for spurious associations in causal inference and, hence, particularly dangerous to the validity of drawn conclusions.

```{r dag}
dag <- dagify(
  lead.time ~ specification + pressure,
  specification ~ pressure,
  exposure = "specification", outcome = "lead.time",
  
  labels = c(specification = "Specification Format", 
             lead.time = "Lead Time", pressure = "Pressure"),
  coords = list(x = c(specification = 0, lead.time = 2, pressure = 1), 
                y = c(specification = 0, lead.time = 0, pressure = 1))
)

ggdag_status(dag, use_labels = "label", text = FALSE) +
  guides(fill = "none", color = "none") + 
  theme_dag()
```

```{r simulation}
n <- 1000 # number of simulated units, i.e., implemented features
effect.spec <- 0
effect.pressure <- -2

d <- data.frame(pressure = rbernoulli(n, 0.3)) %>% 
  mutate(
    specification = rbernoulli(n, 0.8-0.5*pressure),
    lead.time = rnorm(n, effect.spec*specification + effect.pressure*pressure, 1))
```

```{r model-biased}
m1 <- lm( 
  formula = lead.time ~ specification,
  data = d
)

summary(m1)
```

```{r model-controlled}
m2 <- lm( 
  formula = lead.time ~ specification + pressure,
  data = d
)

summary(m2)
```

```{r}
compare.models <- function(m1, m2, name.m1, name.m2) {
  coefs1 <- data.frame(m = name.m1, m1$coefficients)
  coefs1 <- cbind(factor = rownames(coefs1), coefs1) %>% 
    rename(estimate = "m1.coefficients")
  rownames(coefs1) <- 1:nrow(coefs1)
  
  coefs2 <- data.frame(m = name.m2, m2$coefficients)
  coefs2 <- cbind(factor = rownames(coefs2), coefs2) %>% 
    rename(estimate = "m2.coefficients")
  rownames(coefs2) <- 1:nrow(coefs2)
  
  coefs <- rbind(coefs1, coefs2) %>% 
    filter(factor != "(Intercept)")
  
  ci1 <- data.frame(m = name.m1, confint(m1))
  ci1 <- cbind(factor = rownames(ci1), ci1) %>% 
    rename(all_of(c(lower = "X2.5..", upper = "X97.5..")))
  rownames(ci1) <- 1:nrow(ci1)
  
  ci2 <- data.frame(m = name.m2, confint(m2))
  ci2 <- cbind(factor = rownames(ci2), ci2) %>% 
    rename(all_of(c(lower = "X2.5..", upper = "X97.5..")))
  rownames(ci2) <- 1:nrow(ci2)
  
  ci <- rbind(ci1, ci2) %>% 
    filter(factor != "(Intercept)")
  
  return(merge(x = coefs, y = ci, by = c("m", "factor")))
}
```

```{r}
compare.models(m1, m2, name.m1, name.m2) %>% 
  ggplot(aes(y = factor)) +
    geom_point(aes(x = estimate)) + 
    geom_errorbar(aes(xmin = lower, xmax = upper)) +
    geom_vline(xintercept = effect.spec, 
               linetype = "dashed", color = "cyan", size = 0.9) + 
    geom_vline(xintercept = effect.pressure, 
               linetype = "dashed", color = "grey", size = 0.9) + 
    facet_wrap(vars(m), ncol=1) +
  labs(x = "Estimated effect", y = "Factors") +
  scale_y_discrete(labels = c("Pressure", "Specification")) +
  theme_bw()
```


