---
title: "Mediating"
author: "Julian Frattini"
date: "2025-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(ggdag)

# utility methods for extracting coefficient distributions from two models
source("../util/extract-coefficients.R")
```

This notebook visualizes the effect of a mediator (also called *pipe*) in causal inference.

```{r configuration}
varname.a <- "Variable A" # independent variable (binary)
varname.b <- "Variable B" # dependent variable (continuous)
varname.c <- "Variable C" # mediator (continuous)

effect.ab <- 0.5
effect.ac <- 1
effect.cb <- 2
```

```{r dag}
dag <- dagify(
  b ~ a + c , # causal effect of the independent on the dependent variable (both direct and indirect)
  c ~ a, # effect of the independent variable on the mediator
  exposure = "a", outcome = "b",
  
  labels = c(a = varname.a, b = varname.b, c = varname.c),
  coords = list(x = c(a = 0, b = 2, c = 1), 
                y = c(a = 1, b = 1, c = 0))
)

ggdag_status(dag, use_labels = "label", text = FALSE) +
  guides(fill = "none", color = "none") + 
  theme_dag()
```

```{r simulation}
n <- 1000

d <- data.frame(a = rbinom(n, 1, 0.5)) %>% 
  mutate(
    c = rnorm(n, effect.ac*a, 1),
    b = rnorm(n, effect.ab*a + effect.cb*c, 1)
  )
```

```{r model-total}
m1 <- lm(formula = (b ~ a), data = d)
summary(m1)
```

```{r}
ggplot(d, aes(x = b, y = factor(a))) +
  geom_boxplot()
```

```{r}
ggplot(d, aes(x = c, y = b, color = factor(a))) +
  geom_point() + 
  geom_smooth(formula = (y ~ x), method = "lm")
```

```{r model-direct}
m2 <- lm(formula = b ~ a + c, data = d)
summary(m2)
```

```{r visualization-coefficients}
get.coefficient.distributions(m1, m2, "Model m1 (total)", "Model m2 (differentiated)") %>% 
  ggplot(aes(y = factor)) +
    geom_point(aes(x = estimate)) + 
    geom_errorbar(aes(xmin = lower, xmax = upper)) +
    geom_vline(xintercept = effect.ab + effect.ac*effect.cb, 
               linetype = "dashed", color = "cyan", size = 0.9) + 
    geom_vline(xintercept = effect.ab, linetype = "dashed", color = "grey", size = 0.9) + 
    geom_vline(xintercept = effect.ac*effect.cb, linetype = "dashed", color = "grey", size = 0.9) + 
    facet_wrap(vars(model), ncol=1) +
  labs(x = "Estimated effect", y = "Factors") +
  scale_y_discrete(labels = c(varname.a, varname.c)) +
  theme_bw()
```